CREATE TABLE lead_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lead_id TEXT,
  event_type TEXT NOT NULL,
  event_data TEXT,
  created_at TEXT NOT NULL,
  ts TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  day TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d','now')),
  hour TEXT NOT NULL DEFAULT (strftime('%H','now')),
  type TEXT,
  page TEXT,
  service TEXT,
  source TEXT,
  device TEXT,
  city TEXT,
  country TEXT,
  zip TEXT,
  area TEXT,
  session TEXT,
  scroll_pct INTEGER DEFAULT 0,
  duration_ms INTEGER DEFAULT 0,
  referrer TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  gclid TEXT
);

CREATE TABLE leads (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT,
  city TEXT,
  zip TEXT,
  service TEXT,
  page TEXT,
  session TEXT,
  source TEXT DEFAULT 'website',
  message TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);